# Generated by Django 4.0 on 2022-01-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='greenpass',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
