# Generated by Django 3.2.9 on 2021-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='email',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
