# Generated by Django 3.2.9 on 2021-12-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_BusinessOwner',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.IntegerField(default=0),
        ),
    ]
