# Generated by Django 3.2.9 on 2021-12-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211226_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='haveBusiness',
            field=models.BooleanField(default=False),
        ),
    ]
