# Generated by Django 4.0 on 2022-01-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_greenpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
