# Generated by Django 3.2.9 on 2021-12-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_place_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='restrictions',
        ),
        migrations.AddField(
            model_name='place',
            name='restrictions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.restrictions'),
        ),
    ]
