# Generated by Django 3.2.9 on 2021-12-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_havebusiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='haveBusiness',
            field=models.IntegerField(default=0),
        ),
    ]
