# Generated by Django 3.2.9 on 2021-12-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211220_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='restrictions',
        ),
        migrations.AddField(
            model_name='place',
            name='restrictions',
            field=models.ManyToManyField(to='base.Restrictions'),
        ),
    ]
