# Generated by Django 4.0 on 2022-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_place_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='picture',
            field=models.ImageField(default='noimage.png', null=True, upload_to=''),
        ),
    ]
