# Generated by Django 3.2.9 on 2021-12-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_havebusiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='haveBusiness',
            field=models.BooleanField(default=False),
        ),
    ]
