# Generated by Django 3.2.9 on 2022-01-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_place_picture'),
        ('base', '0007_alter_user_havebusiness'),
    ]

    operations = [
    ]
