# Generated by Django 3.2.9 on 2021-12-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_place_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='restrictions',
            field=models.ManyToManyField(to='base.Restrictions', verbose_name='restrictions'),
        ),
    ]
