# Generated by Django 3.2.9 on 2021-12-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211220_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-addedOn', '-lastUpdated']},
        ),
    ]
